In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
from sklearn.datasets import load_iris

In [2]:
Iris = load_iris()
Iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
Iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [17]:
X = Iris['data']
y = Iris['target']

# 설명 변수 데이터를 정규화(normalization)
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)

# 정규화 함수 직접 계산할 때
# iris_df['sepal length (cm)'] = (iris_df['sepal length (cm)'] - iris_df['sepal length (cm)'].mean())/iris_df['sepal length (cm)'].std()
# iris_df['sepal width (cm)'] = (iris_df['sepal width (cm)'] - iris_df['sepal width (cm)'].mean())/iris_df['sepal width (cm)'].std()
# iris_df['petal length (cm)'] =(iris_df['petal length (cm)'] - iris_df['petal length (cm)'].mean())/iris_df['petal length (cm)'].std()
# iris_df['petal width (cm)'] = (iris_df['petal width (cm)'] - iris_df['petal width (cm)'].mean())/iris_df['petal width (cm)'].std()
# iris_df.head()

In [18]:
df = pd.DataFrame(X, columns = Iris['feature_names'])
df['y'] = y

In [19]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  y
0          -0.900681          1.019004          -1.340227         -1.315444  0
1          -1.143017         -0.131979          -1.340227         -1.315444  0
2          -1.385353          0.328414          -1.397064         -1.315444  0
3          -1.506521          0.098217          -1.283389         -1.315444  0
4          -1.021849          1.249201          -1.340227         -1.315444  0

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   y                  150 non-null    int32  
dtypes: float64(4), int32(1)
memory usage: 5.4 KB


In [21]:
# train data와 test data로 구분(7:3 비율)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size = 0.3,
                                                    random_state=10)

In [22]:
from sklearn import svm 

svm_model = svm.SVC(kernel='rbf')

svm_model.fit(X_train, y_train)

SVC()

In [23]:
# test data 가지고 y_hat을 예측(분류)
y_hat= svm_model.predict(X_test)

In [24]:
df = pd.DataFrame({'y_hat':y_hat, 'y':y_test})
df['차이'] = df['y_hat'] == df['y']
df.head()

y_hat  y    차이
0      1  1  True
1      2  2  True
2      0  0  True
3      1  1  True
4      0  0  True

In [25]:
print('오답 수:', len(df) - sum(df['차이']))

오답 수: 0


In [26]:
# 모형 성능 평가 - Confusion Matrix 계산
from sklearn import metrics 
svm_matrix = metrics.confusion_matrix(y_test, y_hat)  
print(svm_matrix)

[[14  0  0]
 [ 0 17  0]
 [ 0  0 14]]


In [27]:
# 모형 성능 평가 - 평가지표 계산
svm_report = metrics.classification_report(y_test, y_hat)            
print(svm_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        17
           2       1.00      1.00      1.00        14

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

